# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3f1bc0a7d7664dd3915a68ed861e7c3e50242b6f4f0c237bc0ffbfd53c23746aa57b5bf7c2666c26ee2f75f43cfce1667d460707317c05c33c734ee4bbcbd78

test:
  secret_key_base: de4cbbcbbdccc2e2308f9f4080975f44c4ab67dc86e5c5f45716089ead158ca689fdc4f526f144562023f2e841b449f1bb3750a07e81ef2a44fce99cf48a4c2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
